# Generated by Django 5.2.17 on 2026-09-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile_create_on_studentprofile_delete_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='create_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='delete_on',
            field=models.DateTimeField(null=True),
        ),
    ]
